### ISSUE TITLE
Primefaces issue

### ISSUE THREAD

**Issue by Parvej86** [liferay/liferay-faces-showcase#95]
The below code is not working for me , Can you please help me. Having problem in Ajax call the managed bean is not called on blur event
<f:facet name="footer">
	<p:inputText id="counter" value="">
									<p:ajax event="blur" update="landingTurnoverList"
										listener="#{negociatedTurnoverController.onNegoSelloutRateTotalEdit(negociatedTurnoverController.sellOuttotal.rateLanding)}" />
								</p:inputText>
							</f:facet>

**Comment by stiemannkj1** [comment]
@Parvej86, please ask your question on [the Liferay Faces Forums](https://web.liferay.com/community/forums/-/message_boards/category/13289029).
